task2: finish second task
satt3l/eduRails pull request #3
Opened 2017-05-23 05:58 UTC by satt3l

2017-05-23 22:53 UTC, psylone requested changes

2017-05-23 22:53 UTC, psylone commented on task2/alphabet.rb
> +iterator = 1
Суть итератора как раз в том чтобы избавиться от счётчиков.

2017-05-23 22:53 UTC, psylone commented on task2/alphabet.rb
> +('a'..'z').each do |letter|
Можно определить массив гласных и итерировать по нему. Это позволит снизить количество итераций.

2017-05-23 22:53 UTC, psylone commented on task2/buy_list.rb
> +  break if input.join.downcase.include?('stop')
Немного странно что строку мы сначала разбиваем, а затем соединяем чтобы узнать нет ли в ней значения `stop`.

2017-05-23 22:53 UTC, psylone commented on task2/buy_list.rb
> +  product_list[input[0]] = { price: price, amount: amount, overall: price * amount }
Что будет если пользователь введёт такой же товар с другим количеством или ценой?

2017-05-23 22:53 UTC, psylone commented on task2/fibonaci.rb
> +    fibonaci_array << (fibonaci_array[last_index] + fibonaci_array[last_index - 1])
Можно использовать отрицательные индексы чтобы брать элементы с конца массива.

2017-05-23 22:53 UTC, psylone commented on task2/fibonaci.rb
> +(1..100).each do |num|
Можем ли мы как-то снизить число итераций, если будем рассматривать сразу сумму 2-х последних элементов и сравнивать её с пороговым значением?

2017-05-23 22:53 UTC, psylone commented on task2/mini_calender.rb
> +monthes.each do |name, days|
Для хэшей есть удобный метод-псевдоним `each_pair`.

2017-05-23 22:53 UTC, psylone commented on task2/get_date.rb
> +puts "Date has order number #{day_index}"
Проверь, например, 21-е апреля 2004:

```ruby
require 'date'
Date.new(2004, 4, 21).strftime('%j')
```

2017-05-25 09:03 UTC, satt3l commented
@psylone поправил, проверь плз как сейчас

2017-05-26 11:03 UTC, psylone approved these changes

2017-05-26 11:03 UTC, psylone commented on task2/alphabet.rb
> +('a'..'z').to_a.each_with_index do |letter, index|
`to_a` можно не вызывать.

2017-05-26 11:03 UTC, psylone commented on task2/buy_list.rb
> +  product_list[product_name] = { price: price, amount: amount, overall: price * amount } if update_allowed
Зачем нам поддерживать флаг, если мы можем сразу в условном выражении выполнить действие:

```ruby
if gets.chomp.downcase == 'update'
  product_list[product_name] = { price: price, amount: amount, overall: price * amount }
end
```

2017-05-26 11:03 UTC, psylone commented on task2/buy_list.rb
> +  update_allowed = true
Нет необходимости заранее присваивать значение `update_allowed`.

2017-05-26 11:03 UTC, psylone commented on task2/buy_list.rb
> +    if gets.chomp.downcase == 'update'
Можно использовать факт того что `if` является выражением и, следовательно, возвращает результат:

```ruby
update_allowed = if gets.chomp.downcase == 'update
  true
else
  false
end
```

Либо через тернарное выражение:

```ruby
update_allowed = gets.chomp.downcase == 'update' ? true : false
```

Но лучше не использовать флаг вовсе )

2017-05-26 11:03 UTC, psylone commented on task2/fibonaci.rb
> +  break if num > MAX_VALUE
Стоит тогда и в диапазоне использовать константу: `(1..MAX_VALUE)`.

2017-05-26 11:03 UTC, psylone commented on task2/fibonaci.rb
> +    fibonaci_array << next_value
Годится, но я бы посмотрел в сторону такой логики:

```ruby
fib = [0, 1]

loop do
  next_element = fib[-2] + fib[-1]
  break if next_element > MAX_ELEMENT_VALUE
  fib.push(next_element)
end
```

2017-05-26 11:03 UTC, psylone commented on task2/get_date.rb
> +puts "Date has order number #{day_index}"
Либо `(year % 100 != 0)`.

2017-05-26 11:03 UTC, psylone commented
Годится, создай пожалуйста новый ответ на Teachbase, чтобы я смог его принять.

2017-05-26 11:12 UTC, satt3l commented on task2/buy_list.rb
> +  product_list[product_name] = { price: price, amount: amount, overall: price * amount } if update_allowed
в этом случае мне придется два раза повторять кусок кода с  product_list[product_name] =....
ибо тут я только делаю апдейт, если уже сущесвует. А я думал использовать флаг именно для того чтобы операция присвоения была единичная, а флаг просто дает знать можно ли это делать

2017-05-27 23:38 UTC, psylone approved these changes

2017-05-29 08:55 UTC, merged

2017-06-22 17:46 UTC, psylone commented on task2/buy_list.rb
> +  product_list[product_name] = { price: price, amount: amount, overall: price * amount } if update_allowed
Если пользователь не разрешает `update`, можно там же в условном выражении вызывать `next`, тогда здесь не будет нужно проверять `if update_allowed` и от флага всё же можно будет избавиться.